#!/bin/sh

cd "$(dirname "$0")/.." || exit 1

bootstrap=
while getopts bh opt; do
    case "$opt" in
        b)
            bootstrap=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
mkdir -p "$XDG_DATA_HOME"/{vim,nvim}{,/backup,/undo} "$XDG_DATA_HOME/nvim/shada"

if ! [ -d pack/bundle/opt/minpac ]; then
    git clone --depth 1 https://github.com/k-takata/minpac pack/bundle/opt/minpac
fi

if command -v nvim >/dev/null 2>&1; then
    cmd=nvim
    set -- ${bootstrap:+--headless}
else
    cmd=vim
    set -- ${bootstrap:+-E}
fi

if [ "$bootstrap" = "1" ]; then
    cat /dev/null
else
    cat /dev/stdin
fi \
    | command "$cmd" "$@" -u vimrc -c PackUpdate${bootstrap:+AndQuit}
echo
